version: '3.8'

services:
  web:
    build: .
    environment:
      - DJANGO_ENV=production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A core worker --loglevel=info
    environment:
      - DJANGO_ENV=production
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info
    environment:
      - DJANGO_ENV=production
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: