application:
  debug: false
  secret_key: ${DJANGO_SECRET_KEY}
  allowed_hosts:
    - ".railway.app"
    - "localhost"
    - "127.0.0.1"

database:
  engine: "django.db.backends.postgresql"
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  host: ${DB_HOST}
  port: ${DB_PORT}

celery:
  broker_url: ${CELERY_BROKER_URL}
  result_backend: ${CELERY_RESULT_BACKEND}

cors:
  allowed_origins:
    - "https://campaign-app-frontend-liard.vercel.app/"
    - "http://localhost:5173"
  allow_credentials: true
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "accept"
    - "accept-encoding"
    - "authorization"
    - "content-type"
    - "dnt"
    - "origin"
    - "user-agent"
    - "x-csrftoken"
    - "x-requested-with"